import {Metadata} from "next"

export const metadata: Metadata = {
  title: "Body On Track",
  description:
    "Welcome to our Calorie Calculator and Weight Predictor! We're your trusted companion on your journey towards a healthier, happier you. Our easy-to-use tools empower you to make informed decisions about your diet and fitness goals.",
  authors: {name: "Kacper Wąsik", url: "https://kacper.wasik.me"},
  keywords: [
    "calorie calculator",
    "weight predictor",
    "health and fitness",
    "diet and nutrition",
    "calorie intake",
    "weight management",
    "BMI calculator",
    "daily calorie goal",
    "fitness journey",
    "weight loss",
    "weight gain",
    "maintain weight",
    "calorie tracking",
    "healthy lifestyle",
    "nutrition planning",
    "personalized profile",
    "edit profile",
    "health goals",
    "goal setting",
    "responsive design",
    "mobile-friendly",
    "empowerment",
    "health and wellness",
    "body profile",
    "progress tracking",
    "fitness tools",
    "health insights",
    "future weight",
    "realistic goals",
    "adjustable goals",
    "calorie count",
    "healthcare",
    "well-being",
    "healthy choices",
    "nutritional guidance",
    "weight management tools",
    "personalized health",
    "health and nutrition advice",
    "health information",
    "weight tracking",
    "calorie balance",
    "nutrition calculator",
    "body weight",
    "healthy living",
    "weight management advice",
    "fitness calculations",
  ],
}
